DjangoApps/urls.py

from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^blog/', include('blog.urls')),
	url(r'^loginapp/', include('loginapp.urls')),
    url(r'^admin/', admin.site.urls),
]

blog/urls.py
from django.conf.urls import url

from . import views
app_name='blog'
urlpatterns=[
	url(r'^$',views.index,name='index'),
	url(r'^post/(?P<post_id>[0-9]+)/$', views.view_post, name='view_post'),
]


loginapp/urls.py
from django.conf.urls import url,include
from . import views

app_name='loginapp'

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^signin/$',views.signin,name='signin'),
	url(r'^logged/$',views.logged,name='logged'),
	url(r'^logout/$',views.logout_user,name='logout_user'),
	url(r'^signup/',views.signup.as_view(),name='signup'),
	
]

blog/models.py
import datetime
from django.db import models
from django.db.models import permalink
from django.utils import timezone
# Create your models here.

class Post(models.Model):
	title=models.CharField(max_length=50)
	body = models.TextField()
	posted=models.DateTimeField('date published')
	author=models.CharField(max_length=30)
	def __str__(self):
		return self.title
	
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    author = models.CharField(max_length=200)
    body = models.TextField()
    posted_date = models.DateTimeField(default=timezone.now)
    '''approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()'''

    def __str__(self):
        return self.body


loginapp/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=('author','body',)
	

loginapp/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields=['username','email','password']

blog/views.py
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404,redirect
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger

from .models import Post,Comment
from .forms import CommentForm
'''from .forms import CommentForm'''
def index(request):
	all_posts=Post.objects.all()
	paginator=Paginator(all_posts,2)

	page=request.GET.get('page')
	try:
		posts=paginator.page(page)
	except PageNotAnInteger:
		posts=paginator.page(1)
	except EmptyPage:
		posts=paginator.page(paginator.num_pages)

	return render(request,'blog/index.html',{'posts':posts})

def view_post(request, post_id):
	post=get_object_or_404(Post,pk=post_id)
	if request.method=='POST':
		form=CommentForm(request.POST)
		if form.is_valid():
			comment=form.save(commit=False)
			comment.post=post
			comment.save()
			return redirect('blog:view_post',post_id=post_id)
	else:
		form=CommentForm()
	return render(request,'blog/view_post.html',{'post':post,'form':form})





loginapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.views.generic import View 
from .forms import UserForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
	return render(request,'loginapp/index.html')



class signup(View):
	form_class=UserForm
	template_name='loginapp/signup.html'

	#display a blank form
	def get(self,request):
		form=self.form_class(None)
		return render(request,self.template_name,{'form':form})

	#process form data
	def post(self,request):
		form=self.form_class(request.POST)

		if form.is_valid():

			user=form.save(commit=False)

			#cleaned data
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			user.set_password(password)
			user.save()

			user=authenticate(username=username,password=password)

			if user is not None:
				if user.is_active:
					login(request,user)
					return render (request,'loginapp/logged.html')


		return render(request,self.template_name,{'form':form})

def signin(request):
	if request.method=="POST":
		username=request.POST['username']
		password=request.POST['password']
		user=authenticate(username=username,password=password)

		if user is not None:
			if user.is_active:
				login(request,user)
				return render(request,'loginapp/logged.html',{'user':request.user})
			else:
				return render(request,'loginapp/signin.html',{'error_message':'Inactive User'})
		else:
			return render (request,'loginapp/signin.html',{'error_message':'Incorrect Username or Password'})

	return render(request,'loginapp/signin.html')


def logged(request):
	if not request.user.is_authenticated():
		form=UserForm()
		return render(request,'loginapp/signup.html',{'form':form,'error_message':'You are not Authenticated'})
	else:
		return render(request,'loginapp/logged.html',{'user':request.user})

def logout_user(request):
	logout(request)
	form=UserForm(request.POST or None)
	return render(request,'loginapp/signin.html',{'form':form})





blog/templates/blog/base.html

<html>
    <head>
        <title>DjangoApps</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'blog:index'  %}">DjangoApps</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'blog:index'  %}">Blog<span class="sr-only">(current)</span></a></li>
        
      </ul>

      <form class="navbar-form navbar-right" role="search" method="get" action="#">
      	<div class="form-group">
      		<input type="text" class="form-control" name="q" value="">
      	</div>
      	<button type="submit" class="btn btn-default">Search</button>
      </form>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>





        <h1>{% block title %}Welcome to my block{% endblock %}</h1>
        {% block content %}

        {% endblock %}
    </body>
</html>



blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}Posts{% endblock %}
{% block content %}
    

    
    <hr>
    {% if posts %}
        <ul>
        {% for p in posts %}
            <h3><li><a href="{% url 'blog:view_post' p.id %}">{{ p.title }}</a></li></h3>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no Posts.</p>
    {% endif %}

<div class="pagination" >
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>


{% endblock %}



blog/templates/blog/view_post.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    
{{ post.body }}
<br>
Posted On-{{post.posted}}
<h3>>>>{{post.author}}</h3>
<hr>

    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
<hr>

<h1>Comments</h1>
{% for comment in post.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.posted_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.body|linebreaks }}</p>
        <hr>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
{% endblock %}


loginapp/templates/loginapp/index.html
<h1>Welcome to Login App</h1>
<a href="{% url 'loginapp:signin' %}">LogIn</a>

loginapp/templates/loginapp/logged.html

<h1>You are logged in {{user.username}}</h1>
<a href="{% url 'loginapp:logout_user' %}">Log out</a>

loginapp/templates/loginapp/signin.html
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'loginapp:signin'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'loginapp:signup' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

loginapp/templates/loginapp/signup.html
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="POST">
{% csrf_token %}
{%for field in form%}
<label>{{field.label_tag}}</label><p>{{field}}</p><br/>
{%endfor%}
<input type="submit" value ="Sign Up"/>
</form>